<a href="https://colab.research.google.com/github/SamShinwari/tensorflow-from-scratch/blob/main/TensorFlow_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Checking TensorFlow Installation

In [ ]:
import tensorflow as tf

print(tf.__version__)

2.20.0


#First Tensor Program

In [ ]:
import tensorflow as tf

x = tf.constant(10)

print(x)

tf.Tensor(10, shape=(), dtype=int32)


#Scalar

A single number is called a scalar.

In [ ]:
x = tf.constant(10)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)

tf.Tensor(10, shape=(), dtype=int32)
()
0
<dtype: 'int32'>


#Vector
###1-dimensional vector

In [ ]:
x = tf.constant([1, 2, 3, 4, 5])

print(x)
print(x.shape)
print(x.ndim)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
(5,)
1


#Matrix

In [ ]:
x = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

print(x)
print(x.shape)
print(x.ndim)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
(2, 3)
2


#3-D Tensor


In [ ]:
x = tf.constant([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(x)
print(x.shape)
print(x.ndim)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
(2, 2, 2)
3


#Basic Tensor Operations

In [ ]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

c = a + b

print(c)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


#More tensor operation

In [ ]:
a = tf.constant([10, 20, 30])
b = tf.constant([2, 5, 10])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

tf.Tensor([12 25 40], shape=(3,), dtype=int32)
tf.Tensor([ 8 15 20], shape=(3,), dtype=int32)
tf.Tensor([ 20 100 300], shape=(3,), dtype=int32)
tf.Tensor([5. 4. 3.], shape=(3,), dtype=float64)


#Day 1 Exercise

Task

Create two TensorFlow tensors:

A = [10, 20, 30, 40, 50]

B = [2, 4, 5, 8, 10]

Then calculate:

A + B
A - B
A * B
A / B

Also print:

A.shape
A.ndim
A.dtype

In [ ]:
a = tf.constant([10,20,30,40,50])
b = tf.constant([2,4,5,8,10])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

print(a.shape)
print(a.ndim)
print(a.dtype)

tf.Tensor([12 24 35 48 60], shape=(5,), dtype=int32)
tf.Tensor([ 8 16 25 32 40], shape=(5,), dtype=int32)
tf.Tensor([ 20  80 150 320 500], shape=(5,), dtype=int32)
tf.Tensor([5. 5. 6. 5. 5.], shape=(5,), dtype=float64)
(5,)
1
<dtype: 'int32'>


#Exercise 2 — Matrix

Create this TensorFlow tensor:

[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]

Then print:

tensor
shape
number of dimensions
data type

In [ ]:
a = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(a.ndim)
print(a.dtype)

(3, 3)
2
<dtype: 'int32'>
